import React, { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "../services/api";
import { getUser } from "../utils/auth";
import "../styles/MyProduce.css";

const EMPTY = { name:"", category:"", description:"", imageUrl:"", quantity:"", unit:"kg", minimumOrder:"1", price:"", grade:"Standard", location:"", harvestDate:"", availableUntil:"" };
const CATEGORIES=["Vegetables","Fruits","Grains","Seeds","Spices","Other"];
const units=["kg","quintal","tonne","piece","bag"];
const iconFor=(c)=>c==="Fruits"?"🍎":c==="Grains"?"🌾":c==="Seeds"?"🌱":c==="Spices"?"🌶️":"🥬";

export default function MyProduce(){
 const navigate=useNavigate(); const farmer=getUser(); const [produce,setProduce]=useState([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [showForm,setShowForm]=useState(false); const [editingId,setEditingId]=useState(null); const [form,setForm]=useState(EMPTY); const [query,setQuery]=useState(""); const [category,setCategory]=useState("All"); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 const load=async()=>{setLoading(true);try{const r=await api.get(`/api/produce/farmer/${farmer._id}`);setProduce(r.data)}catch(e){setError(e.response?.data?.message||"Could not load your produce.")}finally{setLoading(false)}};
 useEffect(()=>{if(farmer?._id)load()},[farmer?._id]);
 const openNew=()=>{setForm({...EMPTY,location:farmer?.farmLocation||""});setEditingId(null);setMessage("");setError("");setShowForm(true)};
 const edit=(item)=>{setForm({...EMPTY,...item,quantity:item.quantity??"",minimumOrder:item.minimumOrder??1,price:item.price??"",availableUntil:item.availableUntil?.slice(0,10)||"",harvestDate:item.harvestDate?.slice(0,10)||""});setEditingId(item._id);setMessage("");setError("");setShowForm(true)};
 const submit=async(e)=>{e.preventDefault();setSaving(true);setMessage("");setError("");try{const payload={...form,quantity:Number(form.quantity),minimumOrder:Number(form.minimumOrder),price:Number(form.price)};const r=editingId?await api.put(`/api/produce/${editingId}`,payload):await api.post("/api/produce/add",payload);setMessage(r.data.message);setShowForm(false);setEditingId(null);setForm(EMPTY);await load()}catch(e){setError(e.response?.data?.message||"Unable to save listing.")}finally{setSaving(false)}};
 const remove=async(id)=>{if(!window.confirm("Delete this produce listing? This cannot be undone."))return;try{await api.delete(`/api/produce/${id}`);setMessage("Produce listing deleted.");setProduce(p=>p.filter(x=>x._id!==id))}catch(e){setError(e.response?.data?.message||"Unable to delete listing.")}};
 const visible=useMemo(()=>produce.filter(x=>(category==="All"||x.category===category)&&x.name.toLowerCase().includes(query.toLowerCase())),[produce,category,query]);
 const totalQty=produce.reduce((s,x)=>s+Number(x.quantity||0),0); const active=produce.filter(x=>x.status==="Available").length;
 return <div className="produce-page"><div className="produce-header"><div><span>🌱 Farmer Workspace</span><h1>My Produce</h1><p>Manage professional listings that buyers can discover and order.</p></div><div className="page-actions"><button className="secondary-page-btn" onClick={()=>navigate("/farmer-dashboard")}>← Dashboard</button><button className="add-produce-main-btn" onClick={openNew}>＋ Add Produce</button></div></div>{message&&<div className="page-alert success">✓ {message}</div>}{error&&<div className="page-alert error">{error}</div>}
 <div className="produce-stats"><div className="produce-stat"><div className="produce-stat-icon">🥬</div><div><span>Total Listings</span><h2>{produce.length}</h2></div></div><div className="produce-stat"><div className="produce-stat-icon">📦</div><div><span>Available Listings</span><h2>{active}</h2></div></div><div className="produce-stat"><div className="produce-stat-icon">⚖️</div><div><span>Total Stock</span><h2>{totalQty.toLocaleString()} kg</h2></div></div></div>
 <div className="produce-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your produce…"/><select value={category} onChange={e=>setCategory(e.target.value)}><option>All</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></div>
 {showForm&&<div className="produce-form-card"><div className="form-title"><div><h2>{editingId?"Edit Produce Listing":"Create a Produce Listing"}</h2><p>Give buyers enough information to make a confident bulk purchase.</p></div><button className="close-form" onClick={()=>setShowForm(false)}>✕</button></div><form onSubmit={submit}><div className="professional-form-grid">{[["name","Produce name","e.g. Fresh Tomatoes"],["quantity","Available quantity","e.g. 500"],["minimumOrder","Minimum order","e.g. 25"],["price","Price per unit","e.g. 28"],["grade","Quality / grade","e.g. Grade A"],["location","Pickup / farm location","e.g. Pune, Maharashtra"],["imageUrl","Image URL (optional)","https://..."]].map(([name,label,placeholder])=><label key={name}>{label}<input name={name} value={form[name]} onChange={e=>setForm({...form,[name]:e.target.value})} placeholder={placeholder} type={name==="quantity"||name==="minimumOrder"||name==="price"?"number":"text"} min={name==="quantity"||name==="minimumOrder"||name==="price"?"0":undefined} required={!["imageUrl"].includes(name)}/></label>)}<label>Category<select name="category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})} required><option value="">Select category</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label>Unit<select name="unit" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})}>{units.map(u=><option key={u}>{u}</option>)}</select></label><label>Harvest date<input type="date" name="harvestDate" value={form.harvestDate} onChange={e=>setForm({...form,harvestDate:e.target.value})}/></label><label>Available until<input type="date" name="availableUntil" value={form.availableUntil} onChange={e=>setForm({...form,availableUntil:e.target.value})} required/></label><label className="full-field">Description<textarea name="description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Describe freshness, packaging, quality, delivery/pickup details…" maxLength={1000}/></label></div><div className="form-actions"><button type="button" className="cancel-form-btn" onClick={()=>setShowForm(false)}>Cancel</button><button type="submit" className="save-produce-btn" disabled={saving}>{saving?"Saving…":editingId?"Save Changes":"Publish Listing"}</button></div></form></div>}
 {loading?<div className="professional-empty">Loading your listings…</div>:visible.length===0?<div className="professional-empty"><div>🌱</div><h2>{produce.length?"No matching listings":"Your marketplace starts here"}</h2><p>{produce.length?"Try another search or category.":"Add your first produce listing so buyers can discover you."}</p>{!produce.length&&<button onClick={openNew}>＋ Add your first listing</button>}</div>:<div className="produce-prof-grid">{visible.map(item=><article className="produce-prof-card" key={item._id}><div className="produce-image">{item.imageUrl?<img src={item.imageUrl} alt={item.name}/>:<span>{iconFor(item.category)}</span>}<span className={`status-pill ${item.status.toLowerCase()}`}>{item.status}</span></div><div className="produce-prof-body"><div className="card-top"><span>{item.category}</span><span>{item.grade||"Standard"}</span></div><h2>{item.name}</h2><p>{item.description||"Fresh bulk produce supplied directly by the farmer."}</p><div className="price-row"><strong>₹{Number(item.price).toLocaleString()} <small>/ {item.unit||"kg"}</small></strong><span>{Number(item.quantity).toLocaleString()} {item.unit||"kg"} available</span></div><div className="meta-row"><span>📍 {item.location||farmer?.farmLocation||"Location not set"}</span><span>Min. {item.minimumOrder||1} {item.unit||"kg"}</span></div><div className="card-actions"><button onClick={()=>edit(item)}>Edit</button><button className="danger" onClick={()=>remove(item._id)}>Delete</button></div></div></article>)}</div>}
 </div>
}
