import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import api from "../services/api";
import { getUser } from "../utils/auth";
import "../styles/Orders.css";

const farmerActions={Pending:["Accepted","Rejected"],Accepted:["Processing"],Processing:["Ready for Pickup"],"Ready for Pickup":["Completed"]};
export default function Orders(){const navigate=useNavigate();const farmer=getUser();const [orders,setOrders]=useState([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [tab,setTab]=useState("All");
 const load=async()=>{setLoading(true);try{const r=await api.get(`/api/orders/farmer/${farmer._id}`);setOrders(r.data)}catch(e){setError(e.response?.data?.message||"Could not load orders.")}finally{setLoading(false)}};useEffect(()=>{if(farmer?._id)load()},[farmer?._id]);
 const update=async(id,status)=>{try{const r=await api.patch(`/api/orders/${id}/status`,{status});setOrders(o=>o.map(x=>x._id===id?r.data.order:x))}catch(e){setError(e.response?.data?.message||"Unable to update order.")}};
 const visible=tab==="All"?orders:orders.filter(o=>o.status===tab); const pending=orders.filter(o=>o.status==="Pending").length; const active=orders.filter(o=>["Accepted","Processing","Ready for Pickup"].includes(o.status)).length; const completed=orders.filter(o=>o.status==="Completed").length;
 return <div className="orders-page"><div className="orders-header"><div><span className="orders-tag">🌾 Farmer Orders</span><h1>Orders</h1><p>Review buyer requests and move each order through your fulfillment workflow.</p></div><button className="back-dashboard-btn" onClick={()=>navigate("/farmer-dashboard")}>← Dashboard</button></div>{error&&<div className="page-alert error">{error}</div>}<div className="order-summary"><div><span>Pending</span><strong>{pending}</strong></div><div><span>In progress</span><strong>{active}</strong></div><div><span>Completed</span><strong>{completed}</strong></div><div><span>Total</span><strong>{orders.length}</strong></div></div><div className="orders-tabs"><button className={tab==="All"?"active-tab":""} onClick={()=>setTab("All")}>All</button><button className={tab==="Pending"?"active-tab":""} onClick={()=>setTab("Pending")}>Pending</button><button className={tab==="Processing"?"active-tab":""} onClick={()=>setTab("Processing")}>Processing</button><button className={tab==="Completed"?"active-tab":""} onClick={()=>setTab("Completed")}>Completed</button></div>{loading?<div className="orders-main-box"><p>Loading orders…</p></div>:visible.length===0?<div className="orders-main-box"><div className="big-order-icon">📦</div><h2>No orders in this view</h2><p>New buyer requests will appear here.</p></div>:<div className="professional-orders">{visible.map(order=><article className="professional-order-card" key={order._id}><div className="order-main"><div className="order-icon">🥬</div><div><span className="order-id">ORDER #{order._id.slice(-6).toUpperCase()}</span><h2>{order.produceName}</h2><p>{order.quantity} {order.unit||"kg"} × ₹{order.price} = <strong>₹{order.totalAmount.toLocaleString()}</strong></p><small>Buyer: {order.buyerName} · {new Date(order.orderDate).toLocaleString()}</small></div></div><div className="order-side"><span className={`order-status status-${order.status.toLowerCase().replace(/\s+/g,"-")}`}>{order.status}</span><div className="order-actions">{(farmerActions[order.status]||[]).map(action=><button key={action} onClick={()=>update(order._id,action)} className={action==="Rejected"?"danger":action==="Completed"?"primary":""}>{action}</button>)}</div></div></article>)}</div>}</div>}
